version: '3.3'

services:
  database:
    image: postgres:9.6.12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 25


  backend:
    build: .
    entrypoint: ../Tests/entrypoint.sh
    depends_on:
      - database
    links:
      - database

