version: '3.7'

services:
  database:
    image: postgres:9.6.12
    expose:
      - "5432"
    
  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    depends_on:
      - database

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    links:
      - database

